package com.przychodniamk2;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

@SpringBootApplication
public class PrzychodniaMk2Application implements CommandLineRunner {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    public UserRepository userRepository;

    public static void main(String[] args) {
        new SpringApplicationBuilder(PrzychodniaMk2Application.class).headless(false).run(args);
    }

    @Override
    public void run(String... args) {
        JFrame frame = new JFrame("Spring Boot Swing App");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300,300);
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS));
        JTextField text = new JTextField("Spring Boot can be used with Swing apps");
        panel.add(text, BorderLayout.CENTER);
        JButton buttSave = new JButton("Zapisz");
        buttSave.addActionListener((ActionEvent action)->{
            User user = new User();

            user.setName("Merry");
            user.setEmail("meriadoc@hobbit.shire");

            userRepository.save(user);
        });
        panel.add(buttSave, BorderLayout.AFTER_LAST_LINE);
        JButton buttShow = new JButton("Pokaz");
        panel.add(buttShow, BorderLayout.AFTER_LAST_LINE);
        frame.setContentPane(panel);
        frame.setVisible(true);
    }
}